### PR TITLE
Add .tiff support

### LINKED ISSUE #61: Support TIFF images

### PR DESCRIPTION
**Pull request by esdoppio**
closes #61

### CODE REVIEW

**Comment by mnquintana** [comment]
Thanks for adding this! 🚀 🎸

**Comment by xhacker** [comment]
Although it’s able to open TIFF images now, it’s not showing anything.

**Comment by mnquintana** [comment]
Ah you're right – this package is relying on native browser support for rendering images, and only Safari renders TIFFs. We'll have to update image-view to do something fancier when encountering unsupported file types.

**Comment by esdoppio** [comment]
And fwiw, I also forgot to add `*.tif`. 😊

**Pull request merged**
