### PR TITLE
Use "zoom to fit" as default

### LINKED ISSUE #55: Option to set "zoom to fit" mode as default
It would be helpful if the user can set the image viewer to enable the "zoom to fit" mode **by default**.

PR #40 implements the "zoom to fit" mode, which is awesome, but the mode is apparently off by default. In some situations the user may want to quickly look through multiple images in a folder and may expect the image viewer to zoom each image to fit **by default**, so he does not need to toggle the "Zoom to fit" button **every time** a new image is opened.

**GIF showing current behavior**

issue

**Atom version:** 1.7.4
**image-view version:** 0.57.0
**OS:** Windows 8.1 64-bit

### PR DESCRIPTION
**Pull request by simurai**
### Description of the Change

Changes the default to automatically resize an image to fit the available space.

Before | After
--- | ---
screen shot 2017-02-03 at 4 05 16 pm | screen shot 2017-02-03 at 4 04 58 pm

- Also disables the "Zoom to fit" button once it's selected. 

### Alternate Designs

It could also be a config, but even then (another PR), "zoom to fit" is still the better default.

### Benefits

Able to see the whole image without having to click buttons.

### Possible Drawbacks

Changes the default and might upset some.

### Applicable Issues

Closes #55

### CODE REVIEW

**Comment by simurai** [comment]
Merge conflict resolved and ready for another 👀 

/cc @BinaryMuse @ungb

**Comment by ungb** [comment]
LGTM! This is unrelated to this PR I suppose, but when the zoom to fit button is "disabled", it still looks like a clickable button to me.  This seems like the case before this pr too.

image

/cc @BinaryMuse  for review

**Comment by simurai** [comment]
> This is unrelated to this PR I suppose, but when the zoom to fit button is "disabled", it still looks like a clickable button to me. This seems like the case before this pr too.

The blue should mean "it's active", but yeah, to be consistent, the "Auto" button should be blue too once you start using the -+ to zoom. Made a new issue about it: https://github.com/atom/image-view/issues/118

**Comment by iolsen** [comment]
@BinaryMuse do you have a few minutes to review this?

**Comment by simurai** [comment]
Ok, now that @TimvdLippe approved, we can merge it. :smile:

On a serious note, it _shouldn't_ be too risky and we have still a few weeks to test on master before it moves to Beta. 🚢

**Comment by TimvdLippe** [comment]
It was the nicest way of saying: "oh yes please" without seeming to nag about reviewing time ;)

**Comment by BinaryMuse** [comment]
Apologies @simurai and @iolsen that this totally slipped off my radar! X_X

**Comment by aioue** [comment]
Was this merged in? Running Atom `1.19.2` and image-view `0.61.2` and zoom-to-fit is not default.

**Comment by Ben3eeE** [comment]
@aioue The fix is in Atom 1.20 currently in beta.

**Pull request merged**
