### PR TITLE
Add Tiff support

### LINKED ISSUE #61: Support TIFF images

### PR DESCRIPTION
**Pull request by TimvdLippe**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Add support for Tiff images. It uses https://github.com/seikichi/tiff.js to convert the image to a data url, such that `<image>` can actually show it.

### Alternate Designs

Use a different library to load the image. This library seemed to work just fine with no issues.

### Benefits

Tiff images are now not shown as binary data, but show the actual image.
image

### Possible Drawbacks

It requires some run-time computation to transform the Tiff image to the data url. For very large images, it could make Atom unresponsive for a short time.

### Applicable Issues

Fixes #61

### CODE REVIEW

**Comment by 50Wliu** [comment]
> For very large images, it could make Atom unresponsive for a short time.

I'm a bit concerned about this - we've been making a real push to improve performance lately.  Is there a way to do an async conversion so it doesn't block?

Also, the tiff.js readme has the following note:
>When you load large tiff file, you will see the error message "Cannot enlarge memory arrays in asm.js"
in such case, please call 'Tiff.initialize({TOTAL_MEMORY: ... })'

That error case needs to be covered.

**Comment by TimvdLippe** [comment]
Sadly I can not work on this PR for the coming months. Feel free to update my branch, it should be open for admins of the repo.

**Comment by TimvdLippe** [comment]
@50Wliu I have addressed the performance concerns. I am not sure how to trigger the warning about `TOTAL_MEMORY`, as I could not get my hands of a Tiff image that would trigger that case.

**Comment by TimvdLippe** [comment]
Friendly ping 😄

**Comment by 50Wliu** [comment]
Will try to take a look soon!

**Comment by TimvdLippe** [comment]
@50Wliu Sorry to keep you bothering, but maybe you could slide this PR in your sprint backlog?

**Comment by 50Wliu** [comment]
First, I tried opening a 56KB TIF file with this PR linked.  Atom froze for around 3/4 of a second while processing the file before successfully displaying it.
image-view-small-tiff-performance

Next, I tried opening a 2.52MB TIF file.  Atom froze for around the same time before displaying the file.
image-view-medium-tiff-performance

Finally, I tried opening a 549MB TIF file.  Atom froze for a bit and then threw the following error:
```
Uncaught abort({}) at Error
    at wf (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:89:367)
    at Vc (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:101:412)
    at ___syscall192 (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:1066:155)
    at Li (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:1575:41)
    at Array.<anonymous> (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:1981:431)
    at rd (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:1146:252)
    at _TIFFOpen (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:3166:490)
    at Object.Yh [as ccall] (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:112:19)
    at new Lb (C:\Users\user\Documents\GitHub\image-view\node_modules\tiff.js\tiff.min.js:3183:87)
    at file:///C:/Users/user/Documents/GitHub/image-view/lib/image-editor-view.js:131:31
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

Files used for testing:
[56KB](https://www.photopea.com/api/img/G4.TIF)
[2.52MB](http://www.fileformat.info/format/tiff/sample/1f37bbd5603048178487ec88b1a6425b/download)
[594MB](http://lroc.sese.asu.edu/data/pr/tiff/wac_nearside.tif)

**Comment by 50Wliu** [comment]
Because my previous comment isn't at all actionable, I decided to compare the TIFF performance with something like PNG.

A 22KB PNG file and a 1.98MB PNG file do not freeze Atom for any noticeable period of time.

Upon attempting to open a 457MB PNG file, Atom froze for approximately 47 seconds before displaying the file.  The performance chart shows "Composite Layers" (and a massive DOM GC) as the main culprit.

Therefore it looks like there are still performance issues when converting a (moderately-sized) Tiff image when compared to other formats.

It would be nice if the Tiff instantiation was wrapped in a try/catch and upon erroring a nice error message would be shown in the image view, but it looks like no such error view exists yet in image-view.  At the very least we should catch it and display our own [error](https://atom.io/docs/api/v1.23.3/NotificationManager#instance-addError) so that we don't get automated issue reports about this.

Files used for testing:
[22KB](http://www.fnordware.com/superpng/pnggradHDrgba.png)
[1.98MB](http://samples.fileformat.info/format/png/sample/24189586535d4d02a8e81523ad5af90e/MARBLE24.PNG?AWSAccessKeyId=0V91BEFA7GM093MEVMG2&Signature=KyhgO1MjWCQkGfKH3%2FazKBsOX24%3D&Expires=1516335357)
[457MB](https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73751/world.topo.bathy.200407.3x21600x21600.C1.png)

**Comment by TimvdLippe** [comment]
@50Wliu Thanks for your review! I have updated this PR to extract the Tiff decompilation logic into a web worker with significant performance improvement. Atom should no longer freeze for a long time.

Sadly I don't have the time and fast internet to download the half Gig image (it was downloading very very slowly), so I will need to test that next week when I have fast internet again at the university. However, I suspect that should be in a much better state now as well.

**Comment by 50Wliu** [comment]
Thanks!  Will test again.

**Comment by TimvdLippe** [comment]
@50Wliu Sorry to bother, but I think I have addressed your previous comments and this is ready for review + merge again. Thanks!

**Comment by lee-dohm** [comment]
I apologize for the team not looking deeper into this sooner. Unfortunately, TIFF support in the image-view package isn't something that we want to maintain long-term.

Apologies for the runaround

Not going to merge this

**Pull request closed without merging**
