### PR TITLE
Prevent zoom percentage lower than 1%

### LINKED ISSUE #59: Zooming in does not always work and Zoom does not preserve aspect ratio
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

If you zoom out too much you are unable to zoom back in until after resizing the Atom window. The zoom back in does not respect the original aspect ratio of the image.
### Steps to Reproduce
1. Open the `image-view` [spec image](https://github.com/atom/image-view/blob/master/spec/fixtures/binary-file.png) in Atom.
2. Zoom out a bunch of times, notice zoom gets stuck at some percentage, for me it was 23% or 15%.
3. (Try to) Zoom in a bunch of times, notice it works only once and then gets stuck, 23% to 38% or 15% to 25%.
4. Resize the Atom window.
5. Zoom in a bunch of times.

Added a gif of reproduction using the `image-view` [spec image](https://github.com/atom/image-view/blob/master/spec/fixtures/binary-file.png), which is 10x10. In this gif I press zoom in several times before resizing the Atom window and none of them work. After resizing the Atom window zoom in works but the image is no longer square.
zoom2

**Expected behavior:** Zooming in to work and aspect ratio to be preserved. Zooming to not be depending on the size of the Atom window.

**Actual behavior:** Zooming in does not work, if you resize the Atom window zoom in works but the aspect ratio of the image is wrong.
### Versions

Atom 1.8.0 on Windows 7
##### apm --version

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 1.9.2.msysgit.0
visual studio`
```
##### atom --version

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

### PR DESCRIPTION
**Pull request by thomasjo**
Fixes #59

/cc @atom/feedback

### CODE REVIEW

**Comment by mnquintana** [comment]
🚢

**Comment by Ben3eeE** [comment]
I don't think this fixes #59, if you look at my gif of repro the zoom percentage is 23/38 when it gets stuck not very small.

I'm just guessing here but does the zoom factor multiply with the displayed size of the image and chrome doesn't display the image as 3.75x3.75 but rather as 3x3 and the same goes for 2.25x2.25 being displayed as 3x3 until you resize the window then it is 3x2, 2x3 or 2x2 depending on how you resized?

Some images:
2 25 size says 3x3
3 75 size says 3x3
2 25 after resize 3x2

**Comment by thomasjo** [comment]
I'm pretty sure this fixes the problem. At least when I tried to reproduce the problem, what I experienced was a rounding off "error" which occured when continuously zooming out. The result was the zoom percentage being rounded off to 0%, after which there was no way to recover since we would always multiply by something that was numerically equivalent to zero.

Please test if this fixes the problem you experienced. At the very least this fixes a tangential issue.
If *your* problem persists after this fix, please let me know.

**Comment by Ben3eeE** [comment]
Sorry, I should have mentioned that I did test and my problem does persist. Can you try to zoom out with the spec image in the image-view repository and see what results you get? https://github.com/atom/image-view/blob/master/spec/fixtures/binary-file.png

For me it gets stuck at 23% zooming out and I can't zoom back in more than once up to 38%

But I am using dev mode out of safe mode with Atom 1.8.0 and a weird computer when testing, so maybe something is wrong on my side. I can test on latest master later to see what results I get there.

d

**Comment by thomasjo** [comment]
Thanks for the follow-up! 🙇 
I can indeed reproduce what you're describing — will fix this issue as well.

**Comment by simurai** [comment]
Currently the scaling is based on the "physical" `width()/height()` of an image: https://github.com/atom/image-view/blob/master/lib/image-editor-view.coffee#L127-L128. But when very small and maybe some kind of rounding to whole pixels, it throws off the original aspect ratio?

Maybe we can remember the original size of an image and then scale based on that?

**Comment by thomasjo** [comment]
Problem is the current system is a little bit flawed due to rounding-off errors and such. I'm working on a PR that transitions to a system with predefined "zoom levels", and thus zooming in and out simply transitions betweens those percentages.

---
_**Side note**: this means we always use the original width and height, hence we are not subjected to accumulated rounding-off errors, etc._

**Comment by Ben3eeE** [comment]
> to a system with predefined "zoom levels"

How would this work with the suggested enhancements of manually writing zoom level? Discussed here:
https://github.com/atom/image-view/pull/40#issuecomment-127486377

**Comment by thomasjo** [comment]
That will still work, along the same lines as "zoom to fit". Of course we'd need to determine what should happen when the user clicks zoom in or out after having set a custom percentage, but that's trivial.

**Pull request merged**
